config/routes.rb
TgiCrm::Application.routes.draw do
  root to: 'application#index'

  get 'app(/*path)' => 'application#app', as: :app

  namespace :api do
    namespace :v1 do

      get  'contacts' => 'contact#index'
      post  'contacts' => 'contact#create'
      get  'contacts/:id' => 'contact#show'
      put  'contacts/:id' => 'contact#update'
      delete  'contacts/:id' => 'contact#destroy'
      get  'contacts/:id/strategic_information' => 'contact#strategic_information'

      get  'products' => 'product#index'
      post  'products' => 'product#create'
      get  'products/:id' => 'product#show'
      put  'products/:id' => 'product#update'
      delete  'products/:id' => 'product#destroy'

      get  'deals' => 'deal#index'
      post  'deals' => 'deal#create'
      get  'deals/:id' => 'deal#show'
      put  'deals/:id' => 'deal#update'
      delete  'deals/:id' => 'deal#destroy'

      get 'dashboard/recent_income' => 'dashboard#recent_income'
      get 'dashboard/last_12_weeks_income_comparison' => 'dashboard#last_12_weeks_income_comparison'
      get 'dashboard/top_products_deals' => 'dashboard#top_products_deals'
      
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  layout false

  before_filter :authenticate_user!, only: [ :app ]

  def index
  end

  def app
    @current_user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/app.html.haml
!!!
%html{ :class => "no-js not-ready" }
  %head
    %meta{ :charset => "utf-8" }
    %title
      tgi

    :javascript
      window.api_token = '#{@current_user.token.token}';

    = javascript_include_tag 'vendor'
    = javascript_include_tag 'iugu-ux'
    = stylesheet_link_tag    'iugu-ux'
    = stylesheet_link_tag    'crm'

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1" }
    %meta{ :name => "apple-mobile-web-app-capable", :content => "yes" }
    %meta{ :name => "apple-mobile-web-status-bar-style", :content => "black" }
    %meta{ 'http-equiv' => 'cleartype', :content => 'on' }
    %meta{ 'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge,chrome=1' }
    %meta{ :name => 'MobileOptimized', :content => '320' }

    %link{:href => "//iugu.com/imgs/favicon.ico", :rel => "icon"}/
    %link{:href => "//iugu.com/imgs/favicon.ico", :rel => "shortcut icon"}/


  %body.iugu-ui.ui-box-background


    %noscript
      .js-warning

    #app

    %script
      (function() { $(function() {
      if (typeof(run_webapp) == 'function')
      i18n.setDefaultLocale('#{current_user.locale}');
      return run_webapp(true);
      });
      }).call(this);

app/views/application/index.html.erb
Pagina da empresa! 
<%= link_to "APP!", app_path %>